@baseUrl = http://localhost:4000
@xmlFile = ./EN16931_Einfach.xml
@headers = Content-Type: application/xml\nAccept-Language: de

### GET request for status
GET {{baseUrl}}/health

### Generate a HTML file from a XML file
POST {{baseUrl}}/convert.html
{{headers}}

< {{xmlFile}}

### Generate a PDF file from a XML file
POST {{baseUrl}}/convert.pdf
{{headers}}

< {{xmlFile}}